# Generated by Django 3.0.8 on 2021-05-08 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OffenceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('treated', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date recorded')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='last updated')),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offence.OffenceCategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
