# Generated by Django 3.0.8 on 2021-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offencecategory',
            options={'verbose_name_plural': 'Offence Categories'},
        ),
        migrations.AlterField(
            model_name='offence',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date recorded'),
        ),
        migrations.AlterField(
            model_name='offence',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='last updated'),
        ),
    ]
